version: '2'
services:

  mysql_db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  php:
    build: ./php
    ports:
      - '8000:80'
    volumes:
      - ../:/var/www
      - ../:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql_db:db
    depends_on:
      - mysql_db

  admin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - '8080:80'
    links:
      - mysql_db:db
    depends_on:
      - mysql_db

volumes:
  db:

